export interface Csvfile {
    lno: string,
    invForLine: string,
    orderNumber: string,
    productCode: string,
    classificationCode: string,
    tariff: string,
    invoiceQty: string,
    uq: string,
    customerQty: string,
    custUQ: string,
    price: string,
    volume: string,
    goodsDesc: string,
    attribute: string,
    customText: string,
    netWeight: string,
    org: string,
    bond: String,
    adjustmentPercent: string,
    quarantineContainer: string,
}
